version: "3.3"

services:

  database_gazin:
    image: postgres
    container_name: database_gazin
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=gazin
      - POSTGRES_DB=gazin_db
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: teste_gazin
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
        - database_gazin
    depends_on:
      - database_gazin

volumes:
  pgdata:
    driver: local